// AUTO-GENERATED: Lista klubów i ścieżek do logo
export const logos = [
  { name: 'Austria Vienna', file: 'Austria - Bundesliga/Austria Vienna.png' },
  { name: 'FC Blau-Weiss Linz', file: 'Austria - Bundesliga/FC Blau-Weiss Linz.png' },
  { name: 'Grazer AK 1902', file: 'Austria - Bundesliga/Grazer AK 1902.png' },
  { name: 'LASK', file: 'Austria - Bundesliga/LASK.png' },
  { name: 'Rapid Vienna', file: 'Austria - Bundesliga/Rapid Vienna.png' },
  { name: 'Red Bull Salzburg', file: 'Austria - Bundesliga/Red Bull Salzburg.png' },
  { name: 'SCR Altach', file: 'Austria - Bundesliga/SCR Altach.png' },
  { name: 'SK Austria Klagenfurt', file: 'Austria - Bundesliga/SK Austria Klagenfurt.png' },
  { name: 'SK Sturm Graz', file: 'Austria - Bundesliga/SK Sturm Graz.png' },
  { name: 'TSV Hartberg', file: 'Austria - Bundesliga/TSV Hartberg.png' },
  { name: 'Wolfsberger AC', file: 'Austria - Bundesliga/Wolfsberger AC.png' },
  { name: 'WSG Tirol', file: 'Austria - Bundesliga/WSG Tirol.png' },
  { name: 'Beerschot VA', file: 'Belgium - Jupiler Pro League/Beerschot VA.png' },
  { name: 'Cercle Brugge', file: 'Belgium - Jupiler Pro League/Cercle Brugge.png' },
  { name: 'Club Brugge KV', file: 'Belgium - Jupiler Pro League/Club Brugge KV.png' },
  { name: 'FCV Dender EH', file: 'Belgium - Jupiler Pro League/FCV Dender EH.png' },
  { name: 'KAA Gent', file: 'Belgium - Jupiler Pro League/KAA Gent.png' },
  { name: 'KRC Genk', file: 'Belgium - Jupiler Pro League/KRC Genk.png' },
  { name: 'KV Kortrijk', file: 'Belgium - Jupiler Pro League/KV Kortrijk.png' },
  { name: 'KV Mechelen', file: 'Belgium - Jupiler Pro League/KV Mechelen.png' },
  { name: 'KVC Westerlo', file: 'Belgium - Jupiler Pro League/KVC Westerlo.png' },
  { name: 'Oud-Heverlee Leuven', file: 'Belgium - Jupiler Pro League/Oud-Heverlee Leuven.png' },
  { name: 'R Charleroi SC', file: 'Belgium - Jupiler Pro League/R Charleroi SC.png' },
  { name: 'Royal Antwerp FC', file: 'Belgium - Jupiler Pro League/Royal Antwerp FC.png' },
  { name: 'RSC Anderlecht', file: 'Belgium - Jupiler Pro League/RSC Anderlecht.png' },
  { name: 'Sint-Truidense VV', file: 'Belgium - Jupiler Pro League/Sint-Truidense VV.png' },
  { name: 'Standard Liège', file: 'Belgium - Jupiler Pro League/Standard Liège.png' },
  { name: 'Union Saint-Gilloise', file: 'Belgium - Jupiler Pro League/Union Saint-Gilloise.png' },
  { name: 'Arda Kardzhali', file: 'Bulgaria - efbet Liga/Arda Kardzhali.png' },
  { name: 'Beroe Stara Zagora', file: 'Bulgaria - efbet Liga/Beroe Stara Zagora.png' },
  { name: 'Botev Plovdiv', file: 'Bulgaria - efbet Liga/Botev Plovdiv.png' },
  { name: 'Botev Vratsa', file: 'Bulgaria - efbet Liga/Botev Vratsa.png' },
  { name: 'Cherno More Varna', file: 'Bulgaria - efbet Liga/Cherno More Varna.png' },
  { name: 'CSKA 1948', file: 'Bulgaria - efbet Liga/CSKA 1948.png' },
  { name: 'CSKA-Sofia', file: 'Bulgaria - efbet Liga/CSKA-Sofia.png' },
  { name: 'Hebar Pazardzhik', file: 'Bulgaria - efbet Liga/Hebar Pazardzhik.png' },
  { name: 'Krumovgrad', file: 'Bulgaria - efbet Liga/Krumovgrad.png' },
  { name: 'Levski Sofia', file: 'Bulgaria - efbet Liga/Levski Sofia.png' },
  { name: 'Lokomotiv Plovdiv', file: 'Bulgaria - efbet Liga/Lokomotiv Plovdiv.png' },
  { name: 'Lokomotiv Sofia', file: 'Bulgaria - efbet Liga/Lokomotiv Sofia.png' },
  { name: 'Ludogorets Razgrad', file: 'Bulgaria - efbet Liga/Ludogorets Razgrad.png' },
  { name: 'Septemvri Sofia', file: 'Bulgaria - efbet Liga/Septemvri Sofia.png' },
  { name: 'Slavia Sofia', file: 'Bulgaria - efbet Liga/Slavia Sofia.png' },
  { name: 'Spartak Varna', file: 'Bulgaria - efbet Liga/Spartak Varna.png' },
  { name: 'GNK Dinamo Zagreb', file: 'Croatia - SuperSport HNL/GNK Dinamo Zagreb.png' },
  { name: 'HNK Gorica', file: 'Croatia - SuperSport HNL/HNK Gorica.png' },
  { name: 'HNK Hajduk Split', file: 'Croatia - SuperSport HNL/HNK Hajduk Split.png' },
  { name: 'HNK Rijeka', file: 'Croatia - SuperSport HNL/HNK Rijeka.png' },
  { name: 'HNK Sibenik', file: 'Croatia - SuperSport HNL/HNK Sibenik.png' },
  { name: 'NK Istra 1961', file: 'Croatia - SuperSport HNL/NK Istra 1961.png' },
  { name: 'NK Lokomotiva Zagreb', file: 'Croatia - SuperSport HNL/NK Lokomotiva Zagreb.png' },
  { name: 'NK Osijek', file: 'Croatia - SuperSport HNL/NK Osijek.png' },
  { name: 'NK Varazdin', file: 'Croatia - SuperSport HNL/NK Varazdin.png' },
  { name: 'Slaven Belupo Koprivnica', file: 'Croatia - SuperSport HNL/Slaven Belupo Koprivnica.png' },
  { name: '1.FC Slovacko', file: 'Czech Republic - Chance Liga/1.FC Slovacko.png' },
  { name: 'AC Sparta Prague', file: 'Czech Republic - Chance Liga/AC Sparta Prague.png' },
  { name: 'Bohemians Prague 1905', file: 'Czech Republic - Chance Liga/Bohemians Prague 1905.png' },
  { name: 'FC Banik Ostrava', file: 'Czech Republic - Chance Liga/FC Banik Ostrava.png' },
  { name: 'FC Hradec Kralove', file: 'Czech Republic - Chance Liga/FC Hradec Kralove.png' },
  { name: 'FC Slovan Liberec', file: 'Czech Republic - Chance Liga/FC Slovan Liberec.png' },
  { name: 'FC Viktoria Plzen', file: 'Czech Republic - Chance Liga/FC Viktoria Plzen.png' },
  { name: 'FK Dukla Prague', file: 'Czech Republic - Chance Liga/FK Dukla Prague.png' },
  { name: 'FK Jablonec', file: 'Czech Republic - Chance Liga/FK Jablonec.png' },
  { name: 'FK Mlada Boleslav', file: 'Czech Republic - Chance Liga/FK Mlada Boleslav.png' },
  { name: 'FK Pardubice', file: 'Czech Republic - Chance Liga/FK Pardubice.png' },
  { name: 'FK Teplice', file: 'Czech Republic - Chance Liga/FK Teplice.png' },
  { name: 'MFK Karvina', file: 'Czech Republic - Chance Liga/MFK Karvina.png' },
  { name: 'SK Dynamo Ceske Budejovice', file: 'Czech Republic - Chance Liga/SK Dynamo Ceske Budejovice.png' },
  { name: 'SK Sigma Olomouc', file: 'Czech Republic - Chance Liga/SK Sigma Olomouc.png' },
  { name: 'SK Slavia Prague', file: 'Czech Republic - Chance Liga/SK Slavia Prague.png' },
  { name: 'Aalborg BK', file: 'Denmark - Superliga/Aalborg BK.png' },
  { name: 'Aarhus GF', file: 'Denmark - Superliga/Aarhus GF.png' },
  { name: 'Bröndby IF', file: 'Denmark - Superliga/Bröndby IF.png' },
  { name: 'FC Copenhagen', file: 'Denmark - Superliga/FC Copenhagen.png' },
  { name: 'FC Midtjylland', file: 'Denmark - Superliga/FC Midtjylland.png' },
  { name: 'FC Nordsjaelland', file: 'Denmark - Superliga/FC Nordsjaelland.png' },
  { name: 'Lyngby BK', file: 'Denmark - Superliga/Lyngby BK.png' },
  { name: 'Randers FC', file: 'Denmark - Superliga/Randers FC.png' },
  { name: 'Silkeborg IF', file: 'Denmark - Superliga/Silkeborg IF.png' },
  { name: 'Sönderjyske', file: 'Denmark - Superliga/Sönderjyske.png' },
  { name: 'Vejle Boldklub', file: 'Denmark - Superliga/Vejle Boldklub.png' },
  { name: 'Viborg FF', file: 'Denmark - Superliga/Viborg FF.png' },
  { name: 'AFC Bournemouth', file: 'England - Premier League/AFC Bournemouth.png' },
  { name: 'Arsenal FC', file: 'England - Premier League/Arsenal FC.png' },
  { name: 'Aston Villa', file: 'England - Premier League/Aston Villa.png' },
  { name: 'Brentford FC', file: 'England - Premier League/Brentford FC.png' },
  { name: 'Brighton & Hove Albion', file: 'England - Premier League/Brighton & Hove Albion.png' },
  { name: 'Chelsea FC', file: 'England - Premier League/Chelsea FC.png' },
  { name: 'Crystal Palace', file: 'England - Premier League/Crystal Palace.png' },
  { name: 'Everton FC', file: 'England - Premier League/Everton FC.png' },
  { name: 'Fulham FC', file: 'England - Premier League/Fulham FC.png' },
  { name: 'Ipswich Town', file: 'England - Premier League/Ipswich Town.png' },
  { name: 'Leicester City', file: 'England - Premier League/Leicester City.png' },
  { name: 'Liverpool FC', file: 'England - Premier League/Liverpool FC.png' },
  { name: 'Manchester City', file: 'England - Premier League/Manchester City.png' },
  { name: 'Manchester United', file: 'England - Premier League/Manchester United.png' },
  { name: 'Newcastle United', file: 'England - Premier League/Newcastle United.png' },
  { name: 'Nottingham Forest', file: 'England - Premier League/Nottingham Forest.png' },
  { name: 'Southampton FC', file: 'England - Premier League/Southampton FC.png' },
  { name: 'Tottenham Hotspur', file: 'England - Premier League/Tottenham Hotspur.png' },
  { name: 'West Ham United', file: 'England - Premier League/West Ham United.png' },
  { name: 'Wolverhampton Wanderers', file: 'England - Premier League/Wolverhampton Wanderers.png' },
  { name: 'AJ Auxerre', file: 'France - Ligue 1/AJ Auxerre.png' },
  { name: 'Angers SCO', file: 'France - Ligue 1/Angers SCO.png' },
  { name: 'AS Monaco', file: 'France - Ligue 1/AS Monaco.png' },
  { name: 'AS Saint-Étienne', file: 'France - Ligue 1/AS Saint-Étienne.png' },
  { name: 'FC Nantes', file: 'France - Ligue 1/FC Nantes.png' },
  { name: 'FC Toulouse', file: 'France - Ligue 1/FC Toulouse.png' },
  { name: 'Le Havre AC', file: 'France - Ligue 1/Le Havre AC.png' },
  { name: 'LOSC Lille', file: 'France - Ligue 1/LOSC Lille.png' },
  { name: 'Montpellier HSC', file: 'France - Ligue 1/Montpellier HSC.png' },
  { name: 'OGC Nice', file: 'France - Ligue 1/OGC Nice.png' },
  { name: 'Olympique Lyon', file: 'France - Ligue 1/Olympique Lyon.png' },
  { name: 'Olympique Marseille', file: 'France - Ligue 1/Olympique Marseille.png' },
  { name: 'Paris Saint-Germain', file: 'France - Ligue 1/Paris Saint-Germain.png' },
  { name: 'RC Lens', file: 'France - Ligue 1/RC Lens.png' },
  { name: 'RC Strasbourg Alsace', file: 'France - Ligue 1/RC Strasbourg Alsace.png' },
  { name: 'Stade Brestois 29', file: 'France - Ligue 1/Stade Brestois 29.png' },
  { name: 'Stade Reims', file: 'France - Ligue 1/Stade Reims.png' },
  { name: 'Stade Rennais FC', file: 'France - Ligue 1/Stade Rennais FC.png' },
  { name: '1.FC Heidenheim 1846', file: 'Germany - Bundesliga/1.FC Heidenheim 1846.png' },
  { name: '1.FC Union Berlin', file: 'Germany - Bundesliga/1.FC Union Berlin.png' },
  { name: '1.FSV Mainz 05', file: 'Germany - Bundesliga/1.FSV Mainz 05.png' },
  { name: 'Bayer 04 Leverkusen', file: 'Germany - Bundesliga/Bayer 04 Leverkusen.png' },
  { name: 'Bayern Munich', file: 'Germany - Bundesliga/Bayern Munich.png' },
  { name: 'Borussia Dortmund', file: 'Germany - Bundesliga/Borussia Dortmund.png' },
  { name: 'Borussia Mönchengladbach', file: 'Germany - Bundesliga/Borussia Mönchengladbach.png' },
  { name: 'Eintracht Frankfurt', file: 'Germany - Bundesliga/Eintracht Frankfurt.png' },
  { name: 'FC Augsburg', file: 'Germany - Bundesliga/FC Augsburg.png' },
  { name: 'FC St. Pauli', file: 'Germany - Bundesliga/FC St. Pauli.png' },
  { name: 'Holstein Kiel', file: 'Germany - Bundesliga/Holstein Kiel.png' },
  { name: 'RB Leipzig', file: 'Germany - Bundesliga/RB Leipzig.png' },
  { name: 'SC Freiburg', file: 'Germany - Bundesliga/SC Freiburg.png' },
  { name: 'SV Werder Bremen', file: 'Germany - Bundesliga/SV Werder Bremen.png' },
  { name: 'TSG 1899 Hoffenheim', file: 'Germany - Bundesliga/TSG 1899 Hoffenheim.png' },
  { name: 'VfB Stuttgart', file: 'Germany - Bundesliga/VfB Stuttgart.png' },
  { name: 'VfL Bochum', file: 'Germany - Bundesliga/VfL Bochum.png' },
  { name: 'VfL Wolfsburg', file: 'Germany - Bundesliga/VfL Wolfsburg.png' },
  { name: 'AEK Athens', file: 'Greece - Super League 1/AEK Athens.png' },
  { name: 'APO Levadiakos', file: 'Greece - Super League 1/APO Levadiakos.png' },
  { name: 'Aris Thessaloniki', file: 'Greece - Super League 1/Aris Thessaloniki.png' },
  { name: 'Asteras Aktor', file: 'Greece - Super League 1/Asteras Aktor.png' },
  { name: 'Athens Kallithea', file: 'Greece - Super League 1/Athens Kallithea.png' },
  { name: 'Atromitos Athens', file: 'Greece - Super League 1/Atromitos Athens.png' },
  { name: 'OFI Crete FC', file: 'Greece - Super League 1/OFI Crete FC.png' },
  { name: 'Olympiacos Piraeus', file: 'Greece - Super League 1/Olympiacos Piraeus.png' },
  { name: 'Panathinaikos FC', file: 'Greece - Super League 1/Panathinaikos FC.png' },
  { name: 'Panetolikos GFS', file: 'Greece - Super League 1/Panetolikos GFS.png' },
  { name: 'Panserraikos', file: 'Greece - Super League 1/Panserraikos.png' },
  { name: 'PAOK Thessaloniki', file: 'Greece - Super League 1/PAOK Thessaloniki.png' },
  { name: 'PAS Lamia 1964', file: 'Greece - Super League 1/PAS Lamia 1964.png' },
  { name: 'Volos NPS', file: 'Greece - Super League 1/Volos NPS.png' },
  { name: 'Debreceni VSC', file: 'Hungary - Nemzeti Bajnokság/Debreceni VSC.png' },
  { name: 'Diósgyőri VTK', file: 'Hungary - Nemzeti Bajnokság/Diósgyőri VTK.png' },
  { name: 'ETO FC Győr', file: 'Hungary - Nemzeti Bajnokság/ETO FC Győr.png' },
  { name: 'Fehérvár FC', file: 'Hungary - Nemzeti Bajnokság/Fehérvár FC.png' },
  { name: 'Ferencvárosi TC', file: 'Hungary - Nemzeti Bajnokság/Ferencvárosi TC.png' },
  { name: 'Kecskeméti TE', file: 'Hungary - Nemzeti Bajnokság/Kecskeméti TE.png' },
  { name: 'MTK Budapest', file: 'Hungary - Nemzeti Bajnokság/MTK Budapest.png' },
  { name: 'Nyíregyháza Spartacus', file: 'Hungary - Nemzeti Bajnokság/Nyíregyháza Spartacus.png' },
  { name: 'Paksi FC', file: 'Hungary - Nemzeti Bajnokság/Paksi FC.png' },
  { name: 'Puskás Akadémia FC', file: 'Hungary - Nemzeti Bajnokság/Puskás Akadémia FC.png' },
  { name: 'Zalaegerszegi TE FC', file: 'Hungary - Nemzeti Bajnokság/Zalaegerszegi TE FC.png' },
  { name: 'Újpest FC', file: 'Hungary - Nemzeti Bajnokság/Újpest FC.png' },
  { name: 'AC Milan', file: 'Italy - Serie A/AC Milan.png' },
  { name: 'AC Monza', file: 'Italy - Serie A/AC Monza.png' },
  { name: 'ACF Fiorentina', file: 'Italy - Serie A/ACF Fiorentina.png' },
  { name: 'AS Roma', file: 'Italy - Serie A/AS Roma.png' },
  { name: 'Atalanta BC', file: 'Italy - Serie A/Atalanta BC.png' },
  { name: 'Bologna FC 1909', file: 'Italy - Serie A/Bologna FC 1909.png' },
  { name: 'Cagliari Calcio', file: 'Italy - Serie A/Cagliari Calcio.png' },
  { name: 'Como 1907', file: 'Italy - Serie A/Como 1907.png' },
  { name: 'FC Empoli', file: 'Italy - Serie A/FC Empoli.png' },
  { name: 'Genoa CFC', file: 'Italy - Serie A/Genoa CFC.png' },
  { name: 'Hellas Verona', file: 'Italy - Serie A/Hellas Verona.png' },
  { name: 'Inter Milan', file: 'Italy - Serie A/Inter Milan.png' },
  { name: 'Juventus FC', file: 'Italy - Serie A/Juventus FC.png' },
  { name: 'Parma Calcio 1913', file: 'Italy - Serie A/Parma Calcio 1913.png' },
  { name: 'SS Lazio', file: 'Italy - Serie A/SS Lazio.png' },
  { name: 'SSC Napoli', file: 'Italy - Serie A/SSC Napoli.png' },
  { name: 'Torino FC', file: 'Italy - Serie A/Torino FC.png' },
  { name: 'Udinese Calcio', file: 'Italy - Serie A/Udinese Calcio.png' },
  { name: 'US Lecce', file: 'Italy - Serie A/US Lecce.png' },
  { name: 'Venezia FC', file: 'Italy - Serie A/Venezia FC.png' },
  { name: 'Ajax Amsterdam', file: 'Netherlands - Eredivisie/Ajax Amsterdam.png' },
  { name: 'Almere City FC', file: 'Netherlands - Eredivisie/Almere City FC.png' },
  { name: 'AZ Alkmaar', file: 'Netherlands - Eredivisie/AZ Alkmaar.png' },
  { name: 'FC Groningen', file: 'Netherlands - Eredivisie/FC Groningen.png' },
  { name: 'FC Utrecht', file: 'Netherlands - Eredivisie/FC Utrecht.png' },
  { name: 'Feyenoord Rotterdam', file: 'Netherlands - Eredivisie/Feyenoord Rotterdam.png' },
  { name: 'Fortuna Sittard', file: 'Netherlands - Eredivisie/Fortuna Sittard.png' },
  { name: 'Go Ahead Eagles', file: 'Netherlands - Eredivisie/Go Ahead Eagles.png' },
  { name: 'Heracles Almelo', file: 'Netherlands - Eredivisie/Heracles Almelo.png' },
  { name: 'NAC Breda', file: 'Netherlands - Eredivisie/NAC Breda.png' },
  { name: 'NEC Nijmegen', file: 'Netherlands - Eredivisie/NEC Nijmegen.png' },
  { name: 'PEC Zwolle', file: 'Netherlands - Eredivisie/PEC Zwolle.png' },
  { name: 'PSV Eindhoven', file: 'Netherlands - Eredivisie/PSV Eindhoven.png' },
  { name: 'RKC Waalwijk', file: 'Netherlands - Eredivisie/RKC Waalwijk.png' },
  { name: 'SC Heerenveen', file: 'Netherlands - Eredivisie/SC Heerenveen.png' },
  { name: 'Sparta Rotterdam', file: 'Netherlands - Eredivisie/Sparta Rotterdam.png' },
  { name: 'Twente Enschede FC', file: 'Netherlands - Eredivisie/Twente Enschede FC.png' },
  { name: 'Willem II Tilburg', file: 'Netherlands - Eredivisie/Willem II Tilburg.png' },
  { name: 'FK Bodø Glimt', file: 'Norway - Eliteserien/FK Bodø Glimt.png' },
  { name: 'FK Haugesund', file: 'Norway - Eliteserien/FK Haugesund.png' },
  { name: 'Fredrikstad FK', file: 'Norway - Eliteserien/Fredrikstad FK.png' },
  { name: 'Hamarkameratene', file: 'Norway - Eliteserien/Hamarkameratene.png' },
  { name: 'KFUM-Kameratene Oslo', file: 'Norway - Eliteserien/KFUM-Kameratene Oslo.png' },
  { name: 'Kristiansund BK', file: 'Norway - Eliteserien/Kristiansund BK.png' },
  { name: 'Lillestrøm SK', file: 'Norway - Eliteserien/Lillestrøm SK.png' },
  { name: 'Molde FK', file: 'Norway - Eliteserien/Molde FK.png' },
  { name: 'Odds BK', file: 'Norway - Eliteserien/Odds BK.png' },
  { name: 'Rosenborg BK', file: 'Norway - Eliteserien/Rosenborg BK.png' },
  { name: 'Sandefjord Fotball', file: 'Norway - Eliteserien/Sandefjord Fotball.png' },
  { name: 'Sarpsborg 08 FF', file: 'Norway - Eliteserien/Sarpsborg 08 FF.png' },
  { name: 'SK Brann', file: 'Norway - Eliteserien/SK Brann.png' },
  { name: 'Strømsgodset IF', file: 'Norway - Eliteserien/Strømsgodset IF.png' },
  { name: 'Tromsø IL', file: 'Norway - Eliteserien/Tromsø IL.png' },
  { name: 'Viking FK', file: 'Norway - Eliteserien/Viking FK.png' },
  { name: 'Cracovia', file: 'Poland - PKO BP Ekstraklasa/Cracovia.png' },
  { name: 'GKS Katowice', file: 'Poland - PKO BP Ekstraklasa/GKS Katowice.png' },
  { name: 'Górnik Zabrze', file: 'Poland - PKO BP Ekstraklasa/Górnik Zabrze.png' },
  { name: 'Jagiellonia Bialystok', file: 'Poland - PKO BP Ekstraklasa/Jagiellonia Bialystok.png' },
  { name: 'Korona Kielce', file: 'Poland - PKO BP Ekstraklasa/Korona Kielce.png' },
  { name: 'Lech Poznan', file: 'Poland - PKO BP Ekstraklasa/Lech Poznan.png' },
  { name: 'Lechia Gdansk', file: 'Poland - PKO BP Ekstraklasa/Lechia Gdansk.png' },
  { name: 'Legia Warszawa', file: 'Poland - PKO BP Ekstraklasa/Legia Warszawa.png' },
  { name: 'Motor Lublin', file: 'Poland - PKO BP Ekstraklasa/Motor Lublin.png' },
  { name: 'Piast Gliwice', file: 'Poland - PKO BP Ekstraklasa/Piast Gliwice.png' },
  { name: 'Pogon Szczecin', file: 'Poland - PKO BP Ekstraklasa/Pogon Szczecin.png' },
  { name: 'Puszcza Niepolomice', file: 'Poland - PKO BP Ekstraklasa/Puszcza Niepolomice.png' },
  { name: 'Radomiak Radom', file: 'Poland - PKO BP Ekstraklasa/Radomiak Radom.png' },
  { name: 'Raków Częstochowa', file: 'Poland - PKO BP Ekstraklasa/Raków Częstochowa.png' },
  { name: 'Slask Wroclaw', file: 'Poland - PKO BP Ekstraklasa/Slask Wroclaw.png' },
  { name: 'Stal Mielec', file: 'Poland - PKO BP Ekstraklasa/Stal Mielec.png' },
  { name: 'Widzew Lodz', file: 'Poland - PKO BP Ekstraklasa/Widzew Lodz.png' },
  { name: 'Zaglebie Lubin', file: 'Poland - PKO BP Ekstraklasa/Zaglebie Lubin.png' },
  { name: 'Avs Futebol', file: 'Portugal - Liga Portugal/Avs Futebol.png' },
  { name: 'Boavista FC', file: 'Portugal - Liga Portugal/Boavista FC.png' },
  { name: 'Casa Pia AC', file: 'Portugal - Liga Portugal/Casa Pia AC.png' },
  { name: 'CD Nacional', file: 'Portugal - Liga Portugal/CD Nacional.png' },
  { name: 'CD Santa Clara', file: 'Portugal - Liga Portugal/CD Santa Clara.png' },
  { name: 'CF Estrela Amadora', file: 'Portugal - Liga Portugal/CF Estrela Amadora.png' },
  { name: 'FC Arouca', file: 'Portugal - Liga Portugal/FC Arouca.png' },
  { name: 'FC Famalicão', file: 'Portugal - Liga Portugal/FC Famalicão.png' },
  { name: 'FC Porto', file: 'Portugal - Liga Portugal/FC Porto.png' },
  { name: 'GD Estoril Praia', file: 'Portugal - Liga Portugal/GD Estoril Praia.png' },
  { name: 'Gil Vicente FC', file: 'Portugal - Liga Portugal/Gil Vicente FC.png' },
  { name: 'Moreirense FC', file: 'Portugal - Liga Portugal/Moreirense FC.png' },
  { name: 'Rio Ave FC', file: 'Portugal - Liga Portugal/Rio Ave FC.png' },
  { name: 'SC Braga', file: 'Portugal - Liga Portugal/SC Braga.png' },
  { name: 'SC Farense', file: 'Portugal - Liga Portugal/SC Farense.png' },
  { name: 'SL Benfica', file: 'Portugal - Liga Portugal/SL Benfica.png' },
  { name: 'Sporting CP', file: 'Portugal - Liga Portugal/Sporting CP.png' },
  { name: 'Vitória Guimarães SC', file: 'Portugal - Liga Portugal/Vitória Guimarães SC.png' },
  { name: 'ACSM Politehnica Iasi', file: 'Romania - SuperLiga/ACSM Politehnica Iasi.png' },
  { name: 'AFC Unirea 04 Slobozia', file: 'Romania - SuperLiga/AFC Unirea 04 Slobozia.png' },
  { name: 'CFR Cluj', file: 'Romania - SuperLiga/CFR Cluj.png' },
  { name: 'CS Universitatea Craiova', file: 'Romania - SuperLiga/CS Universitatea Craiova.png' },
  { name: 'FC Botosani', file: 'Romania - SuperLiga/FC Botosani.png' },
  { name: 'FC Buzău', file: 'Romania - SuperLiga/FC Buzău.png' },
  { name: 'FC Dinamo 1948', file: 'Romania - SuperLiga/FC Dinamo 1948.png' },
  { name: 'FC Hermannstadt', file: 'Romania - SuperLiga/FC Hermannstadt.png' },
  { name: 'FC Rapid 1923', file: 'Romania - SuperLiga/FC Rapid 1923.png' },
  { name: 'FC Universitatea Cluj', file: 'Romania - SuperLiga/FC Universitatea Cluj.png' },
  { name: 'FCSB', file: 'Romania - SuperLiga/FCSB.png' },
  { name: 'FCV Farul Constanta', file: 'Romania - SuperLiga/FCV Farul Constanta.png' },
  { name: 'Petrolul Ploiesti', file: 'Romania - SuperLiga/Petrolul Ploiesti.png' },
  { name: 'SC Otelul Galati', file: 'Romania - SuperLiga/SC Otelul Galati.png' },
  { name: 'Sepsi OSK Sf. Gheorghe', file: 'Romania - SuperLiga/Sepsi OSK Sf. Gheorghe.png' },
  { name: 'UTA Arad', file: 'Romania - SuperLiga/UTA Arad.png' },
  { name: 'Akhmat Grozny', file: 'Russia - Premier Liga/Akhmat Grozny.png' },
  { name: 'Akron Togliatti', file: 'Russia - Premier Liga/Akron Togliatti.png' },
  { name: 'CSKA Moscow', file: 'Russia - Premier Liga/CSKA Moscow.png' },
  { name: 'Dinamo Makhachkala', file: 'Russia - Premier Liga/Dinamo Makhachkala.png' },
  { name: 'Dynamo Moscow', file: 'Russia - Premier Liga/Dynamo Moscow.png' },
  { name: 'Fakel Voronezh', file: 'Russia - Premier Liga/Fakel Voronezh.png' },
  { name: 'FC Khimki', file: 'Russia - Premier Liga/FC Khimki.png' },
  { name: 'FC Krasnodar', file: 'Russia - Premier Liga/FC Krasnodar.png' },
  { name: 'FC Orenburg', file: 'Russia - Premier Liga/FC Orenburg.png' },
  { name: 'FC Pari Nizhniy Novgorod', file: 'Russia - Premier Liga/FC Pari Nizhniy Novgorod.png' },
  { name: 'FC Rostov', file: 'Russia - Premier Liga/FC Rostov.png' },
  { name: 'Krylya Sovetov Samara', file: 'Russia - Premier Liga/Krylya Sovetov Samara.png' },
  { name: 'Lokomotiv Moscow', file: 'Russia - Premier Liga/Lokomotiv Moscow.png' },
  { name: 'Rubin Kazan', file: 'Russia - Premier Liga/Rubin Kazan.png' },
  { name: 'Spartak Moscow', file: 'Russia - Premier Liga/Spartak Moscow.png' },
  { name: 'Zenit St. Petersburg', file: 'Russia - Premier Liga/Zenit St. Petersburg.png' },
  { name: 'Aberdeen FC', file: 'Scotland - Scottish Premiership/Aberdeen FC.png' },
  { name: 'Celtic FC', file: 'Scotland - Scottish Premiership/Celtic FC.png' },
  { name: 'Dundee FC', file: 'Scotland - Scottish Premiership/Dundee FC.png' },
  { name: 'Dundee United FC', file: 'Scotland - Scottish Premiership/Dundee United FC.png' },
  { name: 'Heart of Midlothian FC', file: 'Scotland - Scottish Premiership/Heart of Midlothian FC.png' },
  { name: 'Hibernian FC', file: 'Scotland - Scottish Premiership/Hibernian FC.png' },
  { name: 'Kilmarnock FC', file: 'Scotland - Scottish Premiership/Kilmarnock FC.png' },
  { name: 'Motherwell FC', file: 'Scotland - Scottish Premiership/Motherwell FC.png' },
  { name: 'Rangers FC', file: 'Scotland - Scottish Premiership/Rangers FC.png' },
  { name: 'Ross County FC', file: 'Scotland - Scottish Premiership/Ross County FC.png' },
  { name: 'St. Johnstone FC', file: 'Scotland - Scottish Premiership/St. Johnstone FC.png' },
  { name: 'St. Mirren FC', file: 'Scotland - Scottish Premiership/St. Mirren FC.png' },
  { name: 'FK Cukaricki', file: 'Serbia - Super liga Srbije/FK Cukaricki.png' },
  { name: 'FK IMT Belgrad', file: 'Serbia - Super liga Srbije/FK IMT Belgrad.png' },
  { name: 'FK Jedinstvo Ub', file: 'Serbia - Super liga Srbije/FK Jedinstvo Ub.png' },
  { name: 'FK Mladost Lucani', file: 'Serbia - Super liga Srbije/FK Mladost Lucani.png' },
  { name: 'FK Napredak Krusevac', file: 'Serbia - Super liga Srbije/FK Napredak Krusevac.png' },
  { name: 'FK Novi Pazar', file: 'Serbia - Super liga Srbije/FK Novi Pazar.png' },
  { name: 'FK Partizan Belgrade', file: 'Serbia - Super liga Srbije/FK Partizan Belgrade.png' },
  { name: 'FK Radnicki 1923 Kragujevac', file: 'Serbia - Super liga Srbije/FK Radnicki 1923 Kragujevac.png' },
  { name: 'FK Radnicki Nis', file: 'Serbia - Super liga Srbije/FK Radnicki Nis.png' },
  { name: 'FK Spartak Subotica', file: 'Serbia - Super liga Srbije/FK Spartak Subotica.png' },
  { name: 'FK Tekstilac Odzaci', file: 'Serbia - Super liga Srbije/FK Tekstilac Odzaci.png' },
  { name: 'FK TSC Backa Topola', file: 'Serbia - Super liga Srbije/FK TSC Backa Topola.png' },
  { name: 'FK Vojvodina Novi Sad', file: 'Serbia - Super liga Srbije/FK Vojvodina Novi Sad.png' },
  { name: 'OFK Beograd', file: 'Serbia - Super liga Srbije/OFK Beograd.png' },
  { name: 'Red Star Belgrade', file: 'Serbia - Super liga Srbije/Red Star Belgrade.png' },
  { name: 'Zeleznicar Pancevo', file: 'Serbia - Super liga Srbije/Zeleznicar Pancevo.png' },
  { name: 'Athletic Bilbao', file: 'Spain - LaLiga/Athletic Bilbao.png' },
  { name: 'Atlético de Madrid', file: 'Spain - LaLiga/Atlético de Madrid.png' },
  { name: 'CA Osasuna', file: 'Spain - LaLiga/CA Osasuna.png' },
  { name: 'CD Leganés', file: 'Spain - LaLiga/CD Leganés.png' },
  { name: 'Celta de Vigo', file: 'Spain - LaLiga/Celta de Vigo.png' },
  { name: 'Deportivo Alavés', file: 'Spain - LaLiga/Deportivo Alavés.png' },
  { name: 'FC Barcelona', file: 'Spain - LaLiga/FC Barcelona.png' },
  { name: 'Getafe CF', file: 'Spain - LaLiga/Getafe CF.png' },
  { name: 'Girona FC', file: 'Spain - LaLiga/Girona FC.png' },
  { name: 'Rayo Vallecano', file: 'Spain - LaLiga/Rayo Vallecano.png' },
  { name: 'RCD Espanyol Barcelona', file: 'Spain - LaLiga/RCD Espanyol Barcelona.png' },
  { name: 'RCD Mallorca', file: 'Spain - LaLiga/RCD Mallorca.png' },
  { name: 'Real Betis Balompié', file: 'Spain - LaLiga/Real Betis Balompié.png' },
  { name: 'Real Madrid', file: 'Spain - LaLiga/Real Madrid.png' },
  { name: 'Real Sociedad', file: 'Spain - LaLiga/Real Sociedad.png' },
  { name: 'Real Valladolid CF', file: 'Spain - LaLiga/Real Valladolid CF.png' },
  { name: 'Sevilla FC', file: 'Spain - LaLiga/Sevilla FC.png' },
  { name: 'UD Las Palmas', file: 'Spain - LaLiga/UD Las Palmas.png' },
  { name: 'Valencia CF', file: 'Spain - LaLiga/Valencia CF.png' },
  { name: 'Villarreal CF', file: 'Spain - LaLiga/Villarreal CF.png' },
  { name: 'AIK', file: 'Sweden - Allsvenskan/AIK.png' },
  { name: 'BK Häcken', file: 'Sweden - Allsvenskan/BK Häcken.png' },
  { name: 'Djurgårdens IF', file: 'Sweden - Allsvenskan/Djurgårdens IF.png' },
  { name: 'GAIS', file: 'Sweden - Allsvenskan/GAIS.png' },
  { name: 'Halmstads BK', file: 'Sweden - Allsvenskan/Halmstads BK.png' },
  { name: 'Hammarby IF', file: 'Sweden - Allsvenskan/Hammarby IF.png' },
  { name: 'IF Brommapojkarna', file: 'Sweden - Allsvenskan/IF Brommapojkarna.png' },
  { name: 'IF Elfsborg', file: 'Sweden - Allsvenskan/IF Elfsborg.png' },
  { name: 'IFK Göteborg', file: 'Sweden - Allsvenskan/IFK Göteborg.png' },
  { name: 'IFK Norrköping', file: 'Sweden - Allsvenskan/IFK Norrköping.png' },
  { name: 'IFK Värnamo', file: 'Sweden - Allsvenskan/IFK Värnamo.png' },
  { name: 'IK Sirius', file: 'Sweden - Allsvenskan/IK Sirius.png' },
  { name: 'Kalmar FF', file: 'Sweden - Allsvenskan/Kalmar FF.png' },
  { name: 'Malmö FF', file: 'Sweden - Allsvenskan/Malmö FF.png' },
  { name: 'Mjällby AIF', file: 'Sweden - Allsvenskan/Mjällby AIF.png' },
  { name: 'Västerås SK', file: 'Sweden - Allsvenskan/Västerås SK.png' },
  { name: 'BSC Young Boys', file: 'Switzerland - Super League/BSC Young Boys.png' },
  { name: 'FC Basel 1893', file: 'Switzerland - Super League/FC Basel 1893.png' },
  { name: 'FC Lausanne-Sport', file: 'Switzerland - Super League/FC Lausanne-Sport.png' },
  { name: 'FC Lugano', file: 'Switzerland - Super League/FC Lugano.png' },
  { name: 'FC Luzern', file: 'Switzerland - Super League/FC Luzern.png' },
  { name: 'FC Sion', file: 'Switzerland - Super League/FC Sion.png' },
  { name: 'FC St. Gallen 1879', file: 'Switzerland - Super League/FC St. Gallen 1879.png' },
  { name: 'FC Winterthur', file: 'Switzerland - Super League/FC Winterthur.png' },
  { name: 'FC Zürich', file: 'Switzerland - Super League/FC Zürich.png' },
  { name: 'Grasshopper Club Zurich', file: 'Switzerland - Super League/Grasshopper Club Zurich.png' },
  { name: 'Servette FC', file: 'Switzerland - Super League/Servette FC.png' },
  { name: 'Yverdon Sport FC', file: 'Switzerland - Super League/Yverdon Sport FC.png' },
  { name: 'Adana Demirspor', file: 'Türkiye - Süper Lig/Adana Demirspor.png' },
  { name: 'Alanyaspor', file: 'Türkiye - Süper Lig/Alanyaspor.png' },
  { name: 'Antalyaspor', file: 'Türkiye - Süper Lig/Antalyaspor.png' },
  { name: 'Basaksehir FK', file: 'Türkiye - Süper Lig/Basaksehir FK.png' },
  { name: 'Besiktas JK', file: 'Türkiye - Süper Lig/Besiktas JK.png' },
  { name: 'Bodrum FK', file: 'Türkiye - Süper Lig/Bodrum FK.png' },
  { name: 'Caykur Rizespor', file: 'Türkiye - Süper Lig/Caykur Rizespor.png' },
  { name: 'Eyüpspor', file: 'Türkiye - Süper Lig/Eyüpspor.png' },
  { name: 'Fenerbahce', file: 'Türkiye - Süper Lig/Fenerbahce.png' },
  { name: 'Galatasaray', file: 'Türkiye - Süper Lig/Galatasaray.png' },
  { name: 'Gaziantep FK', file: 'Türkiye - Süper Lig/Gaziantep FK.png' },
  { name: 'Göztepe', file: 'Türkiye - Süper Lig/Göztepe.png' },
  { name: 'Hatayspor', file: 'Türkiye - Süper Lig/Hatayspor.png' },
  { name: 'Kasimpasa', file: 'Türkiye - Süper Lig/Kasimpasa.png' },
  { name: 'Kayserispor', file: 'Türkiye - Süper Lig/Kayserispor.png' },
  { name: 'Konyaspor', file: 'Türkiye - Süper Lig/Konyaspor.png' },
  { name: 'Samsunspor', file: 'Türkiye - Süper Lig/Samsunspor.png' },
  { name: 'Sivasspor', file: 'Türkiye - Süper Lig/Sivasspor.png' },
  { name: 'Trabzonspor', file: 'Türkiye - Süper Lig/Trabzonspor.png' },
  { name: 'Chornomorets Odesa', file: 'Ukraine - Premier Liga/Chornomorets Odesa.png' },
  { name: 'Dynamo Kyiv', file: 'Ukraine - Premier Liga/Dynamo Kyiv.png' },
  { name: 'FC Oleksandriya', file: 'Ukraine - Premier Liga/FC Oleksandriya.png' },
  { name: 'Ingulets Petrove', file: 'Ukraine - Premier Liga/Ingulets Petrove.png' },
  { name: 'Karpaty Lviv', file: 'Ukraine - Premier Liga/Karpaty Lviv.png' },
  { name: 'Kolos Kovalivka', file: 'Ukraine - Premier Liga/Kolos Kovalivka.png' },
  { name: 'Kryvbas Kryvyi Rig', file: 'Ukraine - Premier Liga/Kryvbas Kryvyi Rig.png' },
  { name: 'Livyi Bereg Kyiv', file: 'Ukraine - Premier Liga/Livyi Bereg Kyiv.png' },
  { name: 'LNZ Cherkasy', file: 'Ukraine - Premier Liga/LNZ Cherkasy.png' },
  { name: 'NK Veres Rivne', file: 'Ukraine - Premier Liga/NK Veres Rivne.png' },
  { name: 'Obolon Kyiv', file: 'Ukraine - Premier Liga/Obolon Kyiv.png' },
  { name: 'Polissya Zhytomyr', file: 'Ukraine - Premier Liga/Polissya Zhytomyr.png' },
  { name: 'Rukh Lviv', file: 'Ukraine - Premier Liga/Rukh Lviv.png' },
  { name: 'Shakhtar Donetsk', file: 'Ukraine - Premier Liga/Shakhtar Donetsk.png' },
  { name: 'Vorskla Poltava', file: 'Ukraine - Premier Liga/Vorskla Poltava.png' },
  { name: 'Zorya Lugansk', file: 'Ukraine - Premier Liga/Zorya Lugansk.png' },
];